services:
    web:
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
        image: custom-django-image
        container_name: web-container-django
        ports:
            - "8080:8000"
            - "20022:22"
        volumes:
            - ./:/app